In [1]:
# imports

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from scipy.stats import norm
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.impute import KNNImputer, SimpleImputer
from scipy import stats
import os
import re
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.tools.tools import add_constant
from sklearn.model_selection import train_test_split, cross_val_score, cross_val_predict, KFold, GridSearchCV
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import Ridge, RidgeCV, Lasso, LassoCV



In [2]:
X_train = pd.read_csv('datasets_f/Z_train.csv')
X_test = pd.read_csv('datasets_f/Z_test.csv')
y_train = pd.read_csv('datasets_f/y_train.csv')
y_test =pd.read_csv('datasets_f/y_test.csv')
# all have been standardscaled 

In [3]:
test = pd.read_csv('datasets_f/test.csv')

In [4]:
continuous = ['lot_frontage', 'lot_area', 'mas_vnr_area','bsmt_fin_sf_1', 'bsmt_fin_sf_2', 'bsmt_unf_sf', 'total_bsmt_sf', '1st_flr_sf', '2nd_flr_sf', 'gr_liv_area', 'garage_area', 'wood_deck_sf', 'open_porch_sf', 'enclosed_porch','3ssn_porch', 'screen_porch', 'pool_area', 'misc_val']  
discrete = ['year_built','year_remod/add', 'bsmt_full_bath', 'bsmt_half_bath', 'full_bath','half_bath','bedroom_abv_gr','kitchen_abv_gr','tot_rms_abv_grd','fireplaces','garage_yr_blt', 'garage_cars', 'mo_sold', 'yr_sold'] 
numerical = continuous+discrete 

In [5]:
dummies = ['alley',
 'bldg_type_2fmCon',
 'bldg_type_Duplex',
 'bldg_type_Twnhs',
 'bldg_type_TwnhsE',
 'bsmt_cond',
 'bsmt_exposure',
 'bsmt_fin_type_1',
 'bsmt_fin_type_2',
 'bsmt_qual',
 'central_air_Y',
 'condition_1_Feedr',
 'condition_1_Norm',
 'condition_1_PosA',
 'condition_1_PosN',
 'condition_1_RRAe',
 'condition_1_RRAn',
 'condition_2_Norm',
 'electrical',
 'exter_cond',
 'exter_qual',
 'exterior_1st_BrkFace',
 'exterior_1st_CemntBd',
 'exterior_1st_HdBoard',
 'exterior_1st_MetalSd',
 'exterior_1st_Plywood',
 'exterior_1st_Stucco',
 'exterior_1st_VinylSd',
 'exterior_1st_Wd Sdng',
 'exterior_1st_WdShing',
 'exterior_2nd_BrkFace',
 'exterior_2nd_CmentBd',
 'exterior_2nd_HdBoard',
 'exterior_2nd_ImStucc',
 'exterior_2nd_MetalSd',
 'exterior_2nd_Plywood',
 'exterior_2nd_Stucco',
 'exterior_2nd_VinylSd',
 'exterior_2nd_Wd Sdng',
 'exterior_2nd_Wd Shng',
 'fence',
 'fireplace_qu',
 'foundation_CBlock',
 'foundation_PConc',
 'foundation_Slab',
 'foundation_Stone',
 'foundation_Wood',
 'functional',
 'garage_cond',
 'garage_finish',
 'garage_qual',
 'garage_type_Attchd',
 'garage_type_Basment',
 'garage_type_BuiltIn',
 'garage_type_CarPort',
 'garage_type_Detchd',
 'heating_GasW',
 'heating_Grav',
 'heating_qc',
 'house_style_1.5Unf',
 'house_style_1Story',
 'house_style_2.5Unf',
 'house_style_2Story',
 'house_style_SFoyer',
 'house_style_SLvl',
 'id',
 'kitchen_qual',
 'land_contour_HLS',
 'land_contour_Low',
 'land_contour_Lvl',
 'land_slope',
 'lot_config_CulDSac',
 'lot_config_FR2',
 'lot_config_FR3',
 'lot_config_Inside',
 'lot_shape',
 'low_qual_fin_sf',
 'mas_vnr_type_BrkFace',
 'mas_vnr_type_None',
 'mas_vnr_type_Stone',
 'ms_sub_class',
 'ms_zoning_FV',
 'ms_zoning_RH',
 'ms_zoning_RL',
 'ms_zoning_RM',
 'neighborhood_Blueste',
 'neighborhood_BrDale',
 'neighborhood_BrkSide',
 'neighborhood_ClearCr',
 'neighborhood_CollgCr',
 'neighborhood_Crawfor',
 'neighborhood_Edwards',
 'neighborhood_Gilbert',
 'neighborhood_Greens',
 'neighborhood_IDOTRR',
 'neighborhood_MeadowV',
 'neighborhood_Mitchel',
 'neighborhood_NAmes',
 'neighborhood_NWAmes',
 'neighborhood_NoRidge',
 'neighborhood_NridgHt',
 'neighborhood_OldTown',
 'neighborhood_SWISU',
 'neighborhood_Sawyer',
 'neighborhood_SawyerW',
 'neighborhood_Somerst',
 'neighborhood_StoneBr',
 'neighborhood_Timber',
 'neighborhood_Veenker',
 'overall_cond',
 'overall_qual',
 'paved_drive',
 'pid',
 'roof_matl_Tar&Grv',
 'roof_style_Gable',
 'roof_style_Gambrel',
 'roof_style_Hip',
 'roof_style_Mansard',
 'sale_type_CWD',
 'sale_type_ConLD',
 'sale_type_ConLI',
 'sale_type_ConLw',
 'sale_type_New',
 'sale_type_Oth',
 'sale_type_WD ',
 'street_Pave',
 'utilities']
categorical = dummies 

In [6]:
high_num =['gr_liv_area','year_built','garage_area','total_bsmt_sf','full_bath']

In [7]:
high_cat = ['overall_qual','exter_qual','bsmt_qual', 'foundation_PConc']

# Linear Regression

In [8]:
lr=LinearRegression()
# instantiating our first linear regression

In [9]:
lr.fit(X_train,y_train)
# fitting to all training data

LinearRegression()

In [10]:
lr.score(X_train,y_train)

0.9403631212790503

In [11]:
lr.score(X_test,y_test)
# terrible accuracy score, so will be more specific

-2.978463888076195e+17

In [12]:
# Training RMSE
print('train:', mean_squared_error(y_train, lr.predict(X_train), squared=False))
# Testing RMSE
print('test:', mean_squared_error(y_test, lr.predict(X_test), squared=False))

train: 16102.68442138679
test: 36891486831953.99


In [13]:
cross_val_score(lr, X_train, y_train, cv=5).mean()
# baseline score

-1.5983517286723508e+19

In [14]:
cross_val_score(lr, X_test, y_test, cv=5).mean()

-4.0810425305600235e+23

In [15]:
# lr.predict(test)
# terrible

In [16]:
X_train_numerical= pd.read_csv('datasets_f/numZ_train.csv')
X_test_numerical = pd.read_csv('datasets_f/numZ_test.csv')
test_numerical = pd.read_csv('datasets_f/kagtest.csv')


In [17]:
lr2=LinearRegression()

In [18]:
lr2.fit(X_train_numerical,y_train)
# instantiating and fitting our second linear regression model using just the numerical columns

LinearRegression()

In [19]:
lr2.score(X_train_numerical,y_train)

0.8566504070476163

In [20]:
lr2.score(X_test_numerical,y_test)
# better accuracy score!!

0.8539369315520096

In [21]:
# Training RMSE
print('train:', mean_squared_error(y_train, lr2.predict(X_train_numerical), squared=False))
# Testing RMSE
print('test:', mean_squared_error(y_test, lr2.predict(X_test_numerical), squared=False))

train: 24965.430604585228
test: 25834.50825301229


In [22]:
cross_val_score(lr2, X_train_numerical, y_train, cv=5).mean()

0.8463881947089883

In [23]:
cross_val_score(lr2, X_test_numerical, y_test, cv=5).mean()
# cross val scores are also good but not good enough...lets try again!

0.847537149618077

In [24]:
# lr2.predict(test_numerical)

In [25]:
X_trains = X_train[high_num].copy()

In [26]:
X_tests=X_test[high_num].copy()

In [27]:
lr3=LinearRegression()

In [28]:
lr3.fit(X_trains,y_train)
# instantiating and fitting our third linear regression, but this time we only use the most highly correlated features from the numerical features

LinearRegression()

In [29]:
lr3.score(X_trains,y_train)

0.7961889686329996

In [30]:
lr3.score(X_tests,y_test)
#accuracy increased between train and test, meaning that we created a good model but we want a higher accuracy! we will still use this linear regression in our models though

0.8113119405454938

In [31]:
# lr3.predict(test[high_num])

In [32]:
# Training RMSE
print('train:', mean_squared_error(y_train, lr3.predict(X_trains), squared=False))
# Testing RMSE
print('test:', mean_squared_error(y_test, lr3.predict(X_tests), squared=False))

train: 29768.3437793991
test: 29363.119895962616


In [33]:
cross_val_score(lr3, X_trains, y_train, cv=5).mean()

0.7913313635750076

In [34]:
cross_val_score(lr3, X_tests, y_test, cv=5).mean()
# our cross val score also had a marked increase between training and testing sets!! however it is not high enough

0.8050804658688019

In [35]:
X = X_train[high_num]
X.head()

gr_liv_area  year_built  garage_area  total_bsmt_sf  full_bath
0    -0.176010    0.969791    -0.334023      -0.838936   0.852680
1    -0.332737   -0.553011    -0.552025       0.741727  -1.044172
2    -0.477592   -1.162131     1.323805      -0.778772  -1.044172
3     0.982824    1.071311     2.028509       0.812829   0.852680
4     1.011320    0.868271     0.137469      -0.054074   0.852680

# Polynomial Features

In [36]:
# Instantiate PolynomialFeatures
poly = PolynomialFeatures(include_bias=False)
poly

PolynomialFeatures(include_bias=False)

In [37]:
# Create X_poly
# poly.fit(X)
# X_poly = poly.transform(X)
X_poly = poly.fit_transform(X)

X_poly

array([[-0.17600978,  0.96979085, -0.33402339, ...,  0.70381285,
        -0.7153439 ,  0.72706386],
       [-0.33273733, -0.55301057, -0.55202532, ...,  0.5501586 ,
        -0.77449046,  1.09029555],
       [-0.47759158, -1.16213114,  1.32380529, ...,  0.60648572,
         0.81317198,  1.09029555],
       ...,
       [-0.52271011, -0.62069064, -0.82072538, ...,  0.27347668,
        -0.54604982,  1.09029555],
       [-1.01901401, -0.14693019, -0.9069122 , ...,  2.0360384 ,
         1.48992738,  1.09029555],
       [ 0.25855296,  0.86827075,  0.41630886, ...,  2.02398859,
         1.21308242,  0.72706386]])

In [38]:
# Get the feature names
poly.get_feature_names(high_num)

['gr_liv_area',
 'year_built',
 'garage_area',
 'total_bsmt_sf',
 'full_bath',
 'gr_liv_area^2',
 'gr_liv_area year_built',
 'gr_liv_area garage_area',
 'gr_liv_area total_bsmt_sf',
 'gr_liv_area full_bath',
 'year_built^2',
 'year_built garage_area',
 'year_built total_bsmt_sf',
 'year_built full_bath',
 'garage_area^2',
 'garage_area total_bsmt_sf',
 'garage_area full_bath',
 'total_bsmt_sf^2',
 'total_bsmt_sf full_bath',
 'full_bath^2']

In [39]:
# View X_poly in a DataFrame
X_poly = pd.DataFrame(X_poly, columns=poly.get_feature_names(high_num))
X_poly.head()

gr_liv_area  year_built  garage_area  total_bsmt_sf  full_bath  \
0    -0.176010    0.969791    -0.334023      -0.838936   0.852680   
1    -0.332737   -0.553011    -0.552025       0.741727  -1.044172   
2    -0.477592   -1.162131     1.323805      -0.778772  -1.044172   
3     0.982824    1.071311     2.028509       0.812829   0.852680   
4     1.011320    0.868271     0.137469      -0.054074   0.852680   

   gr_liv_area^2  gr_liv_area year_built  gr_liv_area garage_area  \
0       0.030979               -0.170693                 0.058791   
1       0.110714                0.184007                 0.183679   
2       0.228094                0.555024                -0.632238   
3       0.965943                1.052910                 1.993668   
4       1.022768                0.878100                 0.139025   

   gr_liv_area total_bsmt_sf  gr_liv_area full_bath  year_built^2  \
0                   0.147661              -0.150080      0.940494   
1                  -0.246800               0.347435      0.305821   
2                   0.371935               0.498688      1.350549   
3                   0.798868               0.838035      1.147707   
4                  -0.054686               0.862333      0.753894   

   year_built garage_area  year_built total_bsmt_sf  year_built full_bath  \
0               -0.323933                 -0.813592              0.826922   
1                0.305276                 -0.410183              0.577438   
2               -1.538435                  0.905035              1.213465   
3                2.173164                  0.870793              0.913486   
4                0.119360                 -0.046951              0.740357   

   garage_area^2  garage_area total_bsmt_sf  garage_area full_bath  \
0       0.111572                   0.280224              -0.284815   
1       0.304732                  -0.409452               0.576409   
2       1.752460                  -1.030942              -1.382281   
3       4.114850                   1.648832               1.729670   
4       0.018898                  -0.007433               0.117217   

   total_bsmt_sf^2  total_bsmt_sf full_bath  full_bath^2  
0         0.703813                -0.715344     0.727064  
1         0.550159                -0.774490     1.090296  
2         0.606486                 0.813172     1.090296  
3         0.660691                 0.693084     0.727064  
4         0.002924                -0.046108     0.727064

In [40]:
cross_val_score(lr3, X_poly, y_train).mean()

0.8195874148461773

In [41]:
X1=X_train[high_num+high_cat].copy()

# Ridge

In [42]:
# Instantiate.
ridge_model = Ridge(alpha=100)

# Fit.
ridge_model.fit(X_train, y_train)

# Evaluate model using R2.
print(f"Ridge Training R-Squared: {ridge_model.score(X_train, y_train)}")
print(f"Ridge Testing R-Squared: {ridge_model.score(X_test, y_test)}")

Ridge Training R-Squared: 0.9361190528327696
Ridge Testing R-Squared: 0.910780404486492


In [43]:
ridge_model_scores = cross_val_score(ridge_model, X_train, y_train, cv=5)
ridge_model_scores.mean()

0.9146817682695516

In [44]:
test_ridge_model_scores = cross_val_score(ridge_model, X_test, y_test, cv=5)
test_ridge_model_scores.mean()

0.8951580665726675

In [45]:
# 20 numbers, evenly spaced between 0 and 10
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [46]:
# 20 numbers between 10**0 and 10**3  
np.logspace(0, 3,20)

array([   1.        ,    1.43844989,    2.06913808,    2.97635144,
          4.2813324 ,    6.15848211,    8.8586679 ,   12.74274986,
         18.32980711,   26.36650899,   37.92690191,   54.55594781,
         78.47599704,  112.88378917,  162.37767392,  233.57214691,
        335.98182863,  483.29302386,  695.19279618, 1000.        ])

In [47]:
10**np.linspace(0, 3 , 20)

array([   1.        ,    1.43844989,    2.06913808,    2.97635144,
          4.2813324 ,    6.15848211,    8.8586679 ,   12.74274986,
         18.32980711,   26.36650899,   37.92690191,   54.55594781,
         78.47599704,  112.88378917,  162.37767392,  233.57214691,
        335.98182863,  483.29302386,  695.19279618, 1000.        ])

# Ridge CV

In [48]:
# Set up a list of ridge alphas to check.
# np.logspace generates 100 values equally between 0 and 5,
# then converts them to alphas between 10^0 and 10^5.
r_alphas = np.logspace(0, 5, 100)

# Cross-validate over our list of ridge alphas.
ridge_cv = RidgeCV(alphas=r_alphas, scoring='r2', cv=5)

# Fit model using best ridge alpha!
ridge_cv.fit(X_train, y_train);

In [49]:
# Here is the optimal value of alpha
ridge_cv.alpha_

93.26033468832199

Our `ridge_model` object is actually already the model witht he optimal $\alpha$. Let's get the corresponding value of $R^2$.

In [50]:
print(f"Ridge CV Training R-Squared: {ridge_cv.score(X_train, y_train)}")
print(f"Ridge CV Testing R-Squared: {ridge_cv.score(X_test, y_test)}")

Ridge CV Training R-Squared: 0.936347851169465
Ridge CV Testing R-Squared: 0.9108190893400446


The above model is the same is fitting a single, "regular" Ridge regression with that value alpha!

In [51]:
ridge_2 = Ridge(alpha = ridge_cv.alpha_)
ridge_2.fit(X_train, y_train)

print(f"Train score: {ridge_2.score(X_train, y_train)}")
print(f"Test score: {ridge_2.score(X_test, y_test)}")

Train score: 0.936347851169465
Test score: 0.9108190893400446


In [52]:
ridge_cv.coef_

array([[-2.89087305e+02, -6.66442373e+02, -2.75693500e+03,
         3.03283747e+03,  4.77065652e+03, -5.12192458e+02,
         4.74887788e+02,  0.00000000e+00,  5.36551623e+02,
         9.00686789e+03,  3.03092816e+03,  4.78042084e+03,
         1.85534873e+03,  2.94849174e+03,  4.16929499e+03,
         1.45877191e+02,  1.49792244e+03, -1.49640139e+03,
         2.45432788e+03,  1.95853898e+03,  5.70068881e+03,
         1.04594850e+03, -3.79671929e+02, -1.06470826e+03,
         5.03720325e+03,  7.51152335e+02,  1.19941208e+02,
         5.97477242e+03,  4.77121139e+03, -2.79478547e+02,
         9.22342237e+03,  1.57898715e+03,  0.00000000e+00,
         1.51057477e+03,  1.63941910e+03, -1.86489960e+03,
         0.00000000e+00,  4.18017552e+03,  2.55250907e+03,
         2.50414044e+03,  1.53508119e+03,  2.35023276e+03,
         1.60020442e+03,  1.33735103e+03,  1.80431427e+03,
         3.03064930e+03,  2.57351001e+02, -1.31606541e+03,
         9.72521662e+02,  1.16512674e+03,  9.27484798e+0

In [53]:
ridge_cv_scores = cross_val_score(ridge_cv, X_train, y_train, cv=5)
ridge_cv_scores.mean()

0.9142877961109631

In [54]:
test_ridge_cv_scores = cross_val_score(ridge_cv, X_test, y_test, cv=5)
test_ridge_cv_scores.mean()

0.8947530179372173

# Lasso CV

In [55]:
# Set up a list of Lasso alphas to check.
l_alphas = np.logspace(-3, 0, 100)
# Cross-validate over our list of Lasso alphas.
lasso_cv = LassoCV(alphas=l_alphas, cv=5, max_iter=50_000, n_jobs=-1)

# Fit model using best ridge alpha!
lasso_cv.fit(X_train, y_train);

In [56]:
# An array of values of alphas used in the model 
lasso_cv.alphas

array([0.001     , 0.00107227, 0.00114976, 0.00123285, 0.00132194,
       0.00141747, 0.00151991, 0.00162975, 0.00174753, 0.00187382,
       0.00200923, 0.00215443, 0.00231013, 0.00247708, 0.00265609,
       0.00284804, 0.00305386, 0.00327455, 0.00351119, 0.00376494,
       0.00403702, 0.00432876, 0.00464159, 0.00497702, 0.0053367 ,
       0.00572237, 0.00613591, 0.00657933, 0.0070548 , 0.00756463,
       0.00811131, 0.00869749, 0.00932603, 0.01      , 0.01072267,
       0.01149757, 0.01232847, 0.01321941, 0.01417474, 0.01519911,
       0.01629751, 0.01747528, 0.01873817, 0.02009233, 0.02154435,
       0.0231013 , 0.02477076, 0.02656088, 0.02848036, 0.03053856,
       0.03274549, 0.03511192, 0.03764936, 0.04037017, 0.04328761,
       0.04641589, 0.04977024, 0.05336699, 0.05722368, 0.06135907,
       0.06579332, 0.07054802, 0.07564633, 0.08111308, 0.0869749 ,
       0.09326033, 0.1       , 0.10722672, 0.1149757 , 0.12328467,
       0.13219411, 0.14174742, 0.15199111, 0.16297508, 0.17475

In [57]:
# Here is the optimal value of alpha
lasso_cv.alpha_

1.0

In [58]:
print(f"LASSO Training R-Squared: {lasso_cv.score(X_train, y_train)} ")
print(f"LASSO Testing R-Squared: {lasso_cv.score(X_test, y_test)} ")

LASSO Training R-Squared: 0.9403611019445101 
LASSO Testing R-Squared: 0.9085486257048898 


In [59]:
lasso_cv_scores = cross_val_score(lasso_cv, X_train, y_train, cv=5)
lasso_cv_scores.mean()

0.9098619200678041

In [60]:
test_lasso_cv_scores = cross_val_score(lasso_cv, X_test, y_test, cv=5)
test_lasso_cv_scores.mean()

0.8473628146210304

## Ridge vs LASSO, what's the diff?!
Let's check out the coefficients of the Lasso and Ridge models.

In [61]:
# The Ridge Coefficients
ridge_cv.coef_

array([[-2.89087305e+02, -6.66442373e+02, -2.75693500e+03,
         3.03283747e+03,  4.77065652e+03, -5.12192458e+02,
         4.74887788e+02,  0.00000000e+00,  5.36551623e+02,
         9.00686789e+03,  3.03092816e+03,  4.78042084e+03,
         1.85534873e+03,  2.94849174e+03,  4.16929499e+03,
         1.45877191e+02,  1.49792244e+03, -1.49640139e+03,
         2.45432788e+03,  1.95853898e+03,  5.70068881e+03,
         1.04594850e+03, -3.79671929e+02, -1.06470826e+03,
         5.03720325e+03,  7.51152335e+02,  1.19941208e+02,
         5.97477242e+03,  4.77121139e+03, -2.79478547e+02,
         9.22342237e+03,  1.57898715e+03,  0.00000000e+00,
         1.51057477e+03,  1.63941910e+03, -1.86489960e+03,
         0.00000000e+00,  4.18017552e+03,  2.55250907e+03,
         2.50414044e+03,  1.53508119e+03,  2.35023276e+03,
         1.60020442e+03,  1.33735103e+03,  1.80431427e+03,
         3.03064930e+03,  2.57351001e+02, -1.31606541e+03,
         9.72521662e+02,  1.16512674e+03,  9.27484798e+0

In [62]:
# LASSO coefficients
lasso_cv.coef_

array([ -1891.77266337,   1284.03294955,  -6355.01482499,   2243.28406059,
         5993.18476296,    347.33923291,    827.37480532,      0.        ,
          395.98475817,  10049.54833832,   3971.81046816,   8638.81583898,
         1182.08217376,   3844.03166057,   3698.5662699 ,    140.19417984,
          650.41004587,  -1547.95148486,   2282.66372419,   1228.63053644,
         7687.64803751,   1662.96211945,   -836.71748262,      0.        ,
         4349.22725903,    189.28470095,   -343.67030638,  10172.64523681,
        13352.29898112,    745.60686061,   7244.81482125,   1499.65587362,
            0.        ,   -389.23858997,    766.17284139,  -3230.74925116,
            0.        ,   4112.84961577,   1159.16438189,   2701.23070214,
          430.16114994,   2392.38432413,   1438.24092311,   1167.19987242,
         1191.5486866 ,   2844.53611269,   2566.85080378,  -4290.39988238,
         1111.38102481,   1247.82922787,    740.12681828,    304.98418346,
            0.        ,  

In [63]:
lsss=pd.DataFrame(lasso_cv.coef_,X_train.columns)

In [64]:
rddd=pd.DataFrame(ridge_cv.coef_[0],X_train.columns)

In [65]:
lsss.head()

0
id           -1891.772663
pid           1284.032950
ms_sub_class -6355.014825
lot_frontage  2243.284061
lot_area      5993.184763

In [66]:
rddd.head()

0
id            -289.087305
pid           -666.442373
ms_sub_class -2756.935003
lot_frontage  3032.837471
lot_area      4770.656523

In [67]:
lasso = Lasso()

In [68]:
params = {'alpha': [0.001, 0.01, 0.1, 1.0, 10.0]}

#### Instantiate a GridSearchCV object by passing it an estimator and a param_grid.

In [69]:
lasso_grid = GridSearchCV(lasso, param_grid=params)

In [70]:
lasso_grid

GridSearchCV(estimator=Lasso(),
             param_grid={'alpha': [0.001, 0.01, 0.1, 1.0, 10.0]})

#### Fit it on the training data

In [71]:
lasso_grid.fit(X_train, y_train)

GridSearchCV(estimator=Lasso(),
             param_grid={'alpha': [0.001, 0.01, 0.1, 1.0, 10.0]})

#### Score on the training data

In [72]:
lasso_grid.score(X_train, y_train)

0.9402754860105427

#### See all the results of training

In [73]:
lasso_grid.cv_results_

{'mean_fit_time': array([0.05879683, 0.05126381, 0.05187898, 0.05340648, 0.04755397]),
 'std_fit_time': array([0.0099388 , 0.00059911, 0.00124026, 0.0020517 , 0.0015413 ]),
 'mean_score_time': array([0.0024169 , 0.00223455, 0.00224719, 0.00232391, 0.00213256]),
 'std_score_time': array([1.26914794e-04, 4.50507914e-05, 5.24890509e-05, 7.09176294e-05,
        4.83258875e-05]),
 'param_alpha': masked_array(data=[0.001, 0.01, 0.1, 1.0, 10.0],
              mask=[False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'alpha': 0.001},
  {'alpha': 0.01},
  {'alpha': 0.1},
  {'alpha': 1.0},
  {'alpha': 10.0}],
 'split0_test_score': array([0.90214322, 0.90214448, 0.90215701, 0.90227738, 0.90325183]),
 'split1_test_score': array([0.90316099, 0.90316409, 0.90319477, 0.90349321, 0.90563861]),
 'split2_test_score': array([0.92157083, 0.92157125, 0.9215767 , 0.92164717, 0.92232281]),
 'split3_test_score': array([0.91365198, 0.91365326, 0.91366601, 0.9137

In [74]:
pd.DataFrame(lasso_grid.cv_results_)

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_alpha  \
0       0.058797      0.009939         0.002417        0.000127       0.001   
1       0.051264      0.000599         0.002235        0.000045        0.01   
2       0.051879      0.001240         0.002247        0.000052         0.1   
3       0.053406      0.002052         0.002324        0.000071         1.0   
4       0.047554      0.001541         0.002133        0.000048        10.0   

             params  split0_test_score  split1_test_score  split2_test_score  \
0  {'alpha': 0.001}           0.902143           0.903161           0.921571   
1   {'alpha': 0.01}           0.902144           0.903164           0.921571   
2    {'alpha': 0.1}           0.902157           0.903195           0.921577   
3    {'alpha': 1.0}           0.902277           0.903493           0.921647   
4   {'alpha': 10.0}           0.903252           0.905639           0.922323   

   split3_test_score  split4_test_score  mean_test_score  std_test_score  \
0           0.913652           0.907875         0.909680        0.007207   
1           0.913653           0.907878         0.909682        0.007207   
2           0.913666           0.907902         0.909699        0.007200   
3           0.913789           0.908137         0.909869        0.007147   
4           0.914298           0.910126         0.911127        0.006761   

   rank_test_score  
0                5  
1                4  
2                3  
3                2  
4                1

#### What were the best params?

In [75]:
lasso_grid.best_estimator_

Lasso(alpha=10.0)

In [76]:
lasso_grid.best_params_

{'alpha': 10.0}

#### Make predictions for the test set

In [77]:
y_test_preds = lasso_grid.predict(X_test)
y_test_preds[:10]

array([131100.19043915, 222265.63162926, 287164.99074866, 112540.37768049,
       198617.66681078, 375638.95700835, 169682.43109203, 297104.10953496,
       153845.93456483,  73663.16765162])

#### Score with the MAE, MSE, and RMSE on test set

In [78]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [79]:
print(f'MSE: {mean_squared_error(y_test, y_test_preds)}')
print(f'MAE: {mean_absolute_error(y_test, y_test_preds)}')
print(f'RMSE: {mean_squared_error(y_test, y_test_preds, squared=False)}')

MSE: 414203140.51330435
MAE: 15251.00725461291
RMSE: 20351.981242947928


#### Score the best model on the test data with the default scoring metric

In [80]:
lasso_grid.score(X_test, y_test)

0.9093530056215839

In [81]:
lasso_grid_scores = cross_val_score(lasso_grid, X_train, y_train, cv=5)
lasso_grid_scores.mean()

0.9111274823734081

In [82]:
test_lasso_grid_scores = cross_val_score(lasso_grid, X_test, y_test, cv=5)
test_lasso_grid_scores.mean()

0.8558693410632406

# Ridge GridSearchCV (BEST MODEL AND WHAT I SELECTED)

In [83]:
params = {'alpha': np.logspace(0, 4, 50)}
ridge_grid = GridSearchCV(Ridge(), param_grid=params, n_jobs=-1)
ridge_grid.fit(X_train, y_train)

GridSearchCV(estimator=Ridge(), n_jobs=-1,
             param_grid={'alpha': array([1.00000000e+00, 1.20679264e+00, 1.45634848e+00, 1.75751062e+00,
       2.12095089e+00, 2.55954792e+00, 3.08884360e+00, 3.72759372e+00,
       4.49843267e+00, 5.42867544e+00, 6.55128557e+00, 7.90604321e+00,
       9.54095476e+00, 1.15139540e+01, 1.38949549e+01, 1.67683294e+01,
       2.02358965e+01, 2.44205309e+01, 2.94705170e+...
       9.10298178e+01, 1.09854114e+02, 1.32571137e+02, 1.59985872e+02,
       1.93069773e+02, 2.32995181e+02, 2.81176870e+02, 3.39322177e+02,
       4.09491506e+02, 4.94171336e+02, 5.96362332e+02, 7.19685673e+02,
       8.68511374e+02, 1.04811313e+03, 1.26485522e+03, 1.52641797e+03,
       1.84206997e+03, 2.22299648e+03, 2.68269580e+03, 3.23745754e+03,
       3.90693994e+03, 4.71486636e+03, 5.68986603e+03, 6.86648845e+03,
       8.28642773e+03, 1.00000000e+04])})

In [84]:
yhat = ridge_grid.predict(X_test)
mean_squared_error(y_test, yhat, squared=False)

20185.453398642676

In [85]:
ridge_grid.score(X_test,y_test)
# we love to see it, a ridge gridsearchcv with a high accuracy score..this is what we will be selecting

0.9108303547585516

In [86]:
ridge_grid_scores = cross_val_score(ridge_grid, X_train, y_train, cv=5)
ridge_grid_scores.mean()

0.9141447418732891

In [87]:
test_ridge_grid_scores = cross_val_score(ridge_grid, X_test, y_test, cv=5)
test_ridge_grid_scores.mean()

0.8950168463568338